# Generated by Django 3.1.3 on 2021-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplogs', '0003_map_stamped_county_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='county',
            field=models.CharField(default='Laikipia', max_length=50),
            preserve_default=False,
        ),
    ]
