# Generated by Django 3.1.3 on 2021-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplogs', '0006_map_map_categroy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='map_categroy',
        ),
        migrations.AddField(
            model_name='map',
            name='map_category',
            field=models.CharField(choices=[('Cadastral', 'cadastral map'), ('General Boundary', 'general boundary')], default='Cadastral', max_length=100),
        ),
    ]
