# Generated by Django 3.1.3 on 2021-08-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maplogs', '0008_auto_20210814_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, upload_to='maps/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_category',
            field=models.CharField(choices=[('Cadastral', 'cadastral map'), ('General Boundary', 'general boundary'), ('PDP', 'pdp')], default='Cadastral', max_length=100),
        ),
    ]
